# Nome da aplicação
spring.application.name=Microservice Email

# Configuração do servidor (porta)
server.port=8080

# Configuração do banco de dados PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/emaildb
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

# Configuração do JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Configuração do envio de e-mail
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=ynexus22@gmail.com
spring.mail.password=homc bihc ikey yvve
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true